### PR TITLE
Greek translations in dspace-api-lang

### PR DESCRIPTION
**Pull request by kostisalex**

### CODE REVIEW

**Comment by kostisalex** [comment]
@kshepherd Greek translations for backend

**Review by kominis — APPROVED** [review]
Seems ok

**Review by kstamatis — APPROVED** [review]
Everything seems OK. The translations are based to the context of DSpace and they are not blind translations from English to Greek.

**Comment by tdonohue** [comment]
Merging as this now has two approvals.  Thanks @kostisalex !  (And thanks to @kominis and @kstamatis for your quick reviews)

**Pull request merged**
